@startuml
skinparam classAttributeIconSize 0
hide circle


interface Findable<T> {
    + find(date: LocalDate): ArrayList<T>
}

abstract class StorableList<T> {
    - path: String
    
    + save(): void
    + load(): void

    + {abstract} parse(s: String): T
    + {abstract} unparse(t: T): String
}


class Sleep {
    - startDateTime: LocalDateTime
    - endDateTime: LocalDateTime
    - sleepingDuration: Duration
    - sleepDate: LocalDate

    + Sleep(startDateTime: LocalDateTime, toDateTime: LocalDateTime)
    + getStartDateTime(): LocalDateTime
    + getEndDateTime(): LocalDateTime
    + getSleepDate(): LocalDate
    + getSleepingTime(): LocalTime
    + toString(): String

    - calculateSleepingDuration(): Duration
    - calculateSleepDate(): LocalDate
    - generateSleepingDurationStringOutput(): String
    - generateStartDateTimeStringOutput(): String
    - generateEndDateTimeStringOutput(): String
    - generateSleepDateStringOutput(): String
}

class SleepList {
    + find(date: LocalDate): ArrayList<Sleep>
    + sort(): void
    + filterByTimespan(timeSpan: Goal.TimeSpan): ArrayList<Sleep>
    + getTotalSleepDuration(sleepClass: Class<?>, timeSpan: Goal.TimeSpan): int
    + parse(s: String): Sleep
    + unparse(sleep: Sleep): String
}

SleepList "1" --> "1" StorableList: extends
SleepList "*" ..>  Sleep: : contains
SleepList ..> Findable : implements

@enduml
