@startuml
class Activity {
}

class Run {
}

class Cycle {
}

class Swim {
}

class ActivityList {
}

class Data {
}

Activity <|-- Run
Activity <|-- Cycle
Activity <|-- Swim
ActivityList o-- Activity
Data o-- ActivityList


@enduml
