@startuml
'https://plantuml.com/sequence-diagram
skinparam Style strictuml
skinparam SequenceMessageAlignment center
participant ":AthletiCLI" as AthletiCLI #lightblue
participant ":Parser" as Parser #lightgreen
participant ":dietGoal" as dietGoal #lightyellow
participant ":SetDietGoalCommand" as SetDietGoalCommand #lightpink
participant "temp:dietGoalList" as tempDietGoalList #yellow
participant "data:dietGoalList" as dataDietGoalList #yellow

'autonumber
AthletiCLI++
AthletiCLI -> Parser++ : ParseCommand("set-diet-goal fats/1")
Parser -> Parser++ : ParseDietGoalSetEdit("fats/1")
create tempDietGoalList
Parser -> tempDietGoalList++ : dietGoalList()
tempDietGoalList --> Parser-- : dietGoalList

    loop number of valid new diet goals
    create dietGoal
    Parser -> dietGoal++ : dietGoal()
    dietGoal --> Parser-- : dietGoal
    end

Parser --> Parser-- : dietGoalList
create SetDietGoalCommand
Parser -> SetDietGoalCommand++ : SetDietGoalCommand()
SetDietGoalCommand --> Parser-- : SetDietGoalCommand
Parser --> AthletiCLI-- : SetDietGoalCommand
AthletiCLI -> SetDietGoalCommand++ : execute()

    loop number of valid new diet goals
    SetDietGoalCommand -> dataDietGoalList++ : add()
    dataDietGoalList --> SetDietGoalCommand--
    end

destroy tempDietGoalList
SetDietGoalCommand --> AthletiCLI-- : messages

destroy SetDietGoalCommand

@enduml