@startuml
'https://plantuml.com/sequence-diagram
skinparam Style strictuml
skinparam SequenceMessageAlignment center

!define LOGIC_COLOR #3333C4

participant ":AthletiCLI" as AthletiCLI #orange
participant "Parser" as Parser <<class>> #lightblue
participant "ActivityParser" as ActivityParser <<class>> #lightblue
participant "a:Activity" as Activity #yellow
participant "c:AddActivityCommand" as AddActivityCommand #lightgreen
participant "data:Data" as Data #lightgrey
participant "activities:ActivityList" as activities #lightgrey

AthletiCLI++
AthletiCLI -> Parser++: parseCommand(userInput)
Parser -> ActivityParser++: parseActivity(arguments)
ActivityParser -> Activity++: Activity()
Activity --> ActivityParser--: a
ActivityParser --> Parser--: a
Parser -> AddActivityCommand++: AddActivityCommand(a)
AddActivityCommand --> Parser--: c
Parser --> AthletiCLI--: c

AthletiCLI -> AddActivityCommand++: execute(a, data)
AddActivityCommand -> Data++: getActivities()
'Data --> activities++
'activities --> Data--: activities

Data --> AddActivityCommand--: activities
AddActivityCommand -> activities++: add(a)
activities --> AddActivityCommand--
AddActivityCommand --> AthletiCLI--: message

destroy AddActivityCommand
@enduml
