@startuml
'https://plantuml.com/sequence-diagram
skinparam Style strictuml
skinparam SequenceMessageAlignment center

!define LOGIC_COLOR #3333C4

participant ":AthletiCLI" as AthletiCLI #orange
participant "Parser" as Parser <<class>> #lightblue
participant "ActivityParser" as ActivityParser <<class>> #lightblue
participant "goal:ActivityGoal" as ActivityGoal #yellow
participant "c:SetActivityGoalCommand" as SetActivityGoalCommand #lightgreen
participant "data:Data" as Data #lightgrey
participant "goals:ActivityGoalList" as activityGoals #lightgrey

AthletiCLI++
AthletiCLI -> Parser++: parseCommand(userInput)
Parser -> ActivityParser++: parseActivityGoal(arguments)
ActivityParser -> ActivityGoal++: ActivityGoal()
ActivityGoal --> ActivityParser--: goal
ActivityParser --> Parser--: goal
Parser -> SetActivityGoalCommand++: SetActivityGoalCommand(goal)
SetActivityGoalCommand --> Parser--: c
Parser --> AthletiCLI--: c

AthletiCLI -> SetActivityGoalCommand++: execute(goal, data)
SetActivityGoalCommand -> Data++: getActivityGoals()

Data --> SetActivityGoalCommand--: goals
SetActivityGoalCommand -> activityGoals++: add(goal)
activityGoals --> SetActivityGoalCommand--
SetActivityGoalCommand --> AthletiCLI--: message

destroy SetActivityGoalCommand
@enduml